### ISSUE TITLE
how to limit selected count?just like,if choose count more than max enable count ,the first choice will be cancel

### ISSUE THREAD

**Issue by pokid** [davigmacode/flutter_choice#20]

**Comment by davigmacode** [comment]
Hi there! Here's an example that you might find inspiring: 
https://github.com/davigmacode/flutter_choice/blob/main/example/lib/form/inline.dart

**Comment by pokid** [comment]
> Hi there! Here's an example that you might find inspiring: https://github.com/davigmacode/flutter_choice/blob/main/example/lib/form/inline.dart

i noticed this example，but i want to disabe choose . this example allows continue to choose , it just validate when submitted

**Comment by pokid** [comment]
> Hi there! Here's an example that you might find inspiring: https://github.com/davigmacode/flutter_choice/blob/main/example/lib/form/inline.dart

oh,i found this ,and it solved my problem。i show it to anyone need:`onSelected:(value){
              if (_selecteds!.length<=3){
                state.onSelected(widget.selects[i])(value);
              }
            },`
